// This file was generated by Prisma.
import { defineConfig } from "prisma/config";

import { resolveDatabaseUrl } from "./src/database-url.ts";

export default defineConfig({
    schema: "prisma/schema/base.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url: resolveDatabaseUrl(),
    },
});
